services:
  # MySQL Database
  toko-sembako-db:
    image: mysql:8.0
    container_name: toko-sembako-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toko_sembako
    ports:
      - "3308:3306"
    volumes:
      - toko_sembako_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    container_name: toko-sembako-auth
    build: ./auth-service
    ports:
      - "4003:4003"
    depends_on:
      toko-sembako-db:
        condition: service_healthy

  # Product Service
  product-service:
    container_name: toko-sembako-product
    build: ./product-service
    ports:
      - "5001:5001"
    environment:
      DB_HOST: toko-sembako-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: toko_sembako
    depends_on:
      toko-sembako-db:
        condition: service_healthy

  # Inventory Service
  inventory-service:
    container_name: toko-sembako-inventory
    build: ./inventory-service
    ports:
      - "5000:5000"
    environment:
      DB_HOST: toko-sembako-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: toko_sembako
    depends_on:
      toko-sembako-db:
        condition: service_healthy

  # Order Service
  order-service:
    container_name: toko-sembako-order
    build: ./order-service
    ports:
      - "5002:5002"
    environment:
      DB_HOST: toko-sembako-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: toko_sembako
      PRODUCT_SERVICE_URL: http://product-service:5001/graphql
      INVENTORY_SERVICE_URL: http://inventory-service:5000/graphql
      # Anugerah Resto Integration URL
      ANUGERAH_RESTO_INVENTORY_URL: http://host.docker.internal:4002/graphql
    depends_on:
      toko-sembako-db:
        condition: service_healthy
      product-service:
        condition: service_started
      inventory-service:
        condition: service_started

volumes:
  toko_sembako_data:
