services:
  auth-service:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "4003:4000"

  product-service:
    container_name: product-service
    build: ./product-service
    ports:
      - "4001:4000"

  inventory-service:
    container_name: inventory-service
    build: ./inventory-service
    ports:
      - "4000:4000"

  order-service:
    container_name: order-service
    build: ./order-service
    ports:
      - "4002:4000"
